### ISSUE TITLE
🐛 [Bug]: HEAD router were overlapped by GET router.

### ISSUE THREAD

**Issue by i11010520** [gofiber/fiber#3199] opened 2024-11-11 14:26 UTC
### Bug Description

relative code like this:
```
[main.go]
app := fiber.New()
app.Route("/", action.WebRoutes)

[action.go]
func WebRoutes(g fiber.Router) {
(a)	g.Get("/alive", Alive)
(b)	g.Head("/alive", AliveHead)
}

func Alive(c *fiber.Ctx) error {
	return c.JSON(something)
}
func AliveHead(c *fiber.Ctx) error {
	return c.SendStatus(fiber.StatusNoContent)
}
```
When coding like this, `HEAD` response will be the same header content with `GET`.
`HEAD` response will be the right content unless moving `(b)` before `(a)`.

Is it a bug?

### How to Reproduce

```
[main.go]
app := fiber.New()
app.Route("/", action.WebRoutes)

[action.go]
func WebRoutes(g fiber.Router) {
(a)	g.Get("/alive", Alive)
(b)	g.Head("/alive", AliveHead)
}

func Alive(c *fiber.Ctx) error {
	return c.JSON(something)
}
func AliveHead(c *fiber.Ctx) error {
	return c.SendStatus(fiber.StatusNoContent)
}
```

### Expected Behavior

```
❯ curl -I  http://localhost:3000/alive
HTTP/1.1 204 No Content
```

### Fiber Version

Fiber v2.52.5

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment] 2024-11-11 19:18
@i11010520 When a GET route is defined, we also define a HEAD for it.

**Comment by gaby** [comment] 2024-11-11 19:24
Duplicate of https://github.com/gofiber/fiber/issues/2629#issuecomment-1713362057

**Closed** 2024-11-12 02:27 UTC
Labels: ☢️ Bug
