### ISSUE TITLE
🐛 [Bug]: WARNING: DATA RACE

### ISSUE THREAD

**Issue by prospero78** [gofiber/fiber#2359] opened 2023-03-09 08:09 UTC
### Bug Description

```bash
Read at 0x00c0001e6150 by goroutine 52:
  github.com/gofiber/fiber/v2.(*Route).match()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/nsi_service/vendor/github.com/gofiber/fiber/v2/router.go:81 +0x151

. . . 

Previous write at 0x00c0001e6150 by main goroutine:
  github.com/gofiber/fiber/v2.(*App).register()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/nsi_service/vendor/github.com/gofiber/fiber/v2/router.go:253 +0x6e6
```

### How to Reproduce

1. Go to my HML-page 'getRequest' (show form)
2. Click on mybuttom 'Submit' (in POST-from)
3. Do send POST-request my handler
4. See up -- 'WARNING: DATA RACE'

### Expected Behavior

Sysem of down.

### Fiber Version

v2.42.0 

### Code Snippet (optional)

```go
System of down.
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment] 2023-03-09 08:14
Please send full of your log and code

**Comment by ReneWerner87** [comment] 2023-03-12 08:44
@prospero78 pls provide full log and code examples

**Comment by prospero78** [comment] 2023-03-12 09:42
Ohh... Only after with wikend.

**Comment by ReneWerner87** [comment] 2023-03-12 13:09
Ok

**Comment by prospero78** [comment] 2023-03-14 07:41
Im now ready for replay bag.

```bash
Write at 0x00c00013e940 by goroutine 11:
  sync/atomic.AddInt32()
      /home/user/.gvm/gos/go1.17.13/src/runtime/race_amd64.s:305 +0xb
  sync/atomic.AddUint32()
      <autogenerated>:1 +0x1a
  github.com/gofiber/fiber/v2.(*App).Add()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:757 +0x8a
  github.com/gofiber/fiber/v2.(*App).Head()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:711 +0x4c
  github.com/gofiber/fiber/v2.(*App).Get()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:705 +0x8b

. . . . . .

Previous read at 0x00c00013e940 by goroutine 85:
  github.com/gofiber/fiber/v2.(*App).startupMessage()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/listen.go:308 +0x868
  github.com/gofiber/fiber/v2.(*App).Listen()
      /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/listen.go:73 +0x184

```

Call of my code:

In first case:

```go
	sf := &ServHttp{
		serv:   serv,
		router: serv.WebServer().Router(),
	}
	sf.router.Get("/", sf.get)
```

In two case:

```go
func (sf *WebServer) run() {

	err := sf.fib.Listen(":" + sf.port)
	if err != nil {
		sf.kern.Slog().Errorf("WebServer.run(): err=\n\t%w", err)
	}
}
```

Its like call in one moment run listen and add route.

**Comment by efectn** [comment] 2023-03-14 07:50
> Im now ready for replay bag.
> 
> ```shell
> Write at 0x00c00013e940 by goroutine 11:
>   sync/atomic.AddInt32()
>       /home/user/.gvm/gos/go1.17.13/src/runtime/race_amd64.s:305 +0xb
>   sync/atomic.AddUint32()
>       <autogenerated>:1 +0x1a
>   github.com/gofiber/fiber/v2.(*App).Add()
>       /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:757 +0x8a
>   github.com/gofiber/fiber/v2.(*App).Head()
>       /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:711 +0x4c
>   github.com/gofiber/fiber/v2.(*App).Get()
>       /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/app.go:705 +0x8b
> 
> . . . . . .
> 
> Previous read at 0x00c00013e940 by goroutine 85:
>   github.com/gofiber/fiber/v2.(*App).startupMessage()
>       /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/listen.go:308 +0x868
>   github.com/gofiber/fiber/v2.(*App).Listen()
>       /home/user/coding/gowork/src/gitlab.aescorp.ru/dsp_dev/claim/fnsndscaws_service/vendor/github.com/gofiber/fiber/v2/listen.go:73 +0x184
> ```
> 
> Call of my code:
> 
> In first case:
> 
> ```go
> 	sf := &ServHttp{
> 		serv:   serv,
> 		router: serv.WebServer().Router(),
> 	}
> 	sf.router.Get("/", sf.get)
> ```
> 
> In two case:
> 
> ```go
> func (sf *WebServer) run() {
> 
> 	err := sf.fib.Listen(":" + sf.port)
> 	if err != nil {
> 		sf.kern.Slog().Errorf("WebServer.run(): err=\n\t%w", err)
> 	}
> }
> ```
> 
> Its like call in one moment run listen and add route.

You should run Listen after adding all the routes. Otherwise, it'll cause a data race.

**Comment by ReneWerner87** [comment] 2023-03-14 08:15
exactly the server must first be completely configured and then no more routes can be added

we do not support dynamic adding or removing of routes after it has been started

For performance reasons
-> for more information and possible solutions please look into the closed issues

**Comment by ReneWerner87** [comment] 2023-03-14 10:35
@prospero78 can you reduce the problem to an example which is very small and can be executed without any additional files (i.e. a reproducible example)?

then we can tell you where the problem is, otherwise it's hard (we don't have any further information about why or how the code looks like that causes the problems)

**Comment by prospero78** [comment] 2023-03-14 12:31
Im list part code for You. Its problem solved with extract router in safe-trhead type. Im already create this. Its not comfort for coding, and its work. Im not nuderstand what you not make this before all coding.

**Comment by ReneWerner87** [comment] 2023-03-14 13:08
unfortunately did not get all the way through the last comment

clearly you have already disclosed parts of your code, but not the use of these, where then the problem occurs

in the race detection stack trace it looks like you are doing the registering of the routes and starting the app asyncron, which is not supposed to work, because this can lead to expected problems(so we will not do this thread safe)

the app must be created, then the route must be registered and after that you can start the app

doing the setup in parallel doesn't bring any benefit for the server run, just more possibilities for it to break, also the startup should only be slightly faster(unless you have more than 100 routes)

in the comment you seem to write that you could fix your problem, if that is the case then please close this issue

**Closed** 2023-03-14 13:21 UTC
Labels: ☢️ Bug
