### ISSUE TITLE
🐛  Can't find index.html with PathPrefix?

### ISSUE THREAD

**Issue by rayterrill** [gofiber/fiber#1439] opened 2021-07-15 16:35 UTC
**Fiber version**
v2.14.0

**Issue description**
Getting a 404 trying to browse to / mounting a React app using PathPrefix and Index

**Code snippet**

```go
package main

import (
	"embed"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
)

// Embed build directory
//go:embed ui/build/*
var embedDirReact embed.FS

func main() {
	app := fiber.New()

	//serve basic api route returning data
	app.Get("/ping", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	//serve react app
	app.Use("/", filesystem.New(filesystem.Config{
		Root: http.FS(embedDirReact),
		PathPrefix: "ui/build",
		Index: "index.html",
	}))
	
	app.Listen(":3000")
}
```

Result:
Cannot GET /

Browsing to http://localhost:3000/index.html directly works fine.

**Comment by ReneWerner87** [comment] 2021-07-15 18:39
The pathPrefix is used in front of the index path. Please test it with

"index.html"

**Comment by rayterrill** [comment] 2021-07-15 19:02
@ReneWerner87 sorry mate - i played around a ton with this and tried that just to see if it worked. Updated my config above to be the actual one I have (my fault), and it's the same behavior.

**Comment by wirepair** [comment] 2021-07-16 06:37
I'm having a similar problem, what's weird is:
```
//go:embed static/favicon.ico
var faviconFile embed.FS

//go:embed static/*
var embedDirStatic embed.FS

...
	app.Use("/", filesystem.New(filesystem.Config{
		Root:       http.FS(embedDirStatic),
		PathPrefix: "",
		Browse:     false,
		Index:      "static/index.html",
	}))

	app.Use(favicon.New(favicon.ConfigDefault))
```

Works just fine treating index.html as the index. But I can't access `GET /index.html`, I have to access `GET /static/index.html`.

If I set PathPrefix to "static" or "static/" then it stops working, but I can access `GET /index.html`.

**Comment by wirepair** [comment] 2021-07-16 07:18
Ah, I think I figured it out, it's due to how the paths are being prefixed with `/` in filesystem.go

You can easily reproduce this with:
```
test := http.FS(embedDirStatic)
_, err := test.Open("/static/")
if err != nil {
	log.Fatal("boop") // will get called
}

vs 
test := http.FS(embedDirStatic)
_, err := test.Open("static")
if err != nil {
	log.Fatal("boop") // will not get called
}
```

Here's the offending code filesystem.go#L91:
```
	if cfg.PathPrefix != "" && !strings.HasPrefix(cfg.PathPrefix, "/") {
		cfg.PathPrefix = "/" + cfg.PathPrefix
	}
```

**Comment by ReneWerner87** [comment] 2021-07-16 07:26
yes, i also found the errors, the filesytem middleware is not yet fully ready for embedded filesystems

these filesystems behave a little bit different, so the index file can not be found, if i have time today, i will try to provide a fix

**Comment by rayterrill** [comment] 2021-07-16 15:45
Thanks both of y'all. I'm coming over to Golang from NodeJS and Express and I have to say Fiber has been a real treat to work with. ❤️

**Comment by ReneWerner87** [comment] 2021-07-16 18:09
didn't make it today unfortunately, try to provide a fix on the weekend, if you have time before and find a solution, then feel free to create a pull request

**Comment by wirepair** [comment] 2021-07-19 11:09
I took a crack at fixing this, but we are unfortunately out of luck testing the `cfg.Root` underlying type. With embed it's actually an internal type (http.ioFS) so we can't type check it :(.

I tried with: 

```
  // non http.Dir types (embed.FS) should not prefix
  _, shouldPrefix := cfg.Root.(http.Dir)
  ... 
  return func(c *fiber.Ctx) (err error) {
    ...
    // Strip prefix
    path := strings.TrimPrefix(c.Path(), prefix)
    if !shouldPrefix {
        path = strings.TrimPrefix(path, "/")
    } else if !strings.HasPrefix(path, "/") {
        path = "/" + path
    }
   ...
}
```

But i'm worried that all the other filesystems would fail with this. One option is to have a cfg option of ShouldStripPrefix set to false, but can be enabled for different file system types (but that's super ugly too).

Not sure the best way to fix this without requiring additional information from the caller.

**Comment by wirepair** [comment] 2021-07-19 11:37
Super janky, but it's a work around:
```
//go:embed testdata/*
var testEmbedDirStatic embed.FS

// For wrapping embed.FS to suffix any trailing / directories
// with an index.html
type EmbedFS struct {
	f embed.FS
}

// append / to any 'directories' that are opened
func (embed *EmbedFS) Open(name string) (fs.File, error) {
	if strings.HasSuffix(name, "/") {
		name += "index.html"
	}
	return embed.f.Open(name)
}

// wrap the embed.FS in &EmbedFS{...} and pass that to http.FS
func Setup(...) {
	app.Use("/embed", New(Config{
		Root:       http.FS(&EmbedFS{testEmbedDirStatic}),
		PathPrefix: "testdata",
		Index:      "index.html",
	}))
}
```

**Comment by kobenauf** [comment] 2021-08-21 17:03
This seems possibly related to #1490.

The workaround above wouldn't work for this situation:

```
\orgs
    [id].html
orgs.html
```
Fiber looks for \orgs\index.html, but if it's not there, does not find orgs.html, and instead says reading the directory is Forbidden.

**Comment by imraan-go** [comment] 2021-08-22 05:49
> This seems possibly related to #1490.
> 
> The workaround above wouldn't work for a situation where there's a directory without an index file but that does have an html file with the same name as the directory (this is how NextJs exports project structures by the way):
> 
> ```
> \orgs
> \orgs\[id].html
> orgs.html
> ```
> 
> Fiber looks for \orgs\index.html, but if it's not there, does not find orgs.html, and instead says reading the directory '\orgs' is Forbidden.

If that's the case, you can overwrite index file with `fiber.Static{}`.

**Comment by goliatone** [comment] 2021-09-14 03:24
I ran into this issue today, what I saw is the same behavior @wirepair described, the `Open` fails due to `PathPrefix` having a `/` suffix. 
If your `PathPrefix` is `testdata` then this check fails:

```go
file, err = cfg.Root.Open("/testdata/")
```

We could add an extra check after we add the prefix:

```go
if path != "/" && strings.HasSuffix(path, "/") {
	path = strings.TrimSuffix(path, "/")
}
```

**Comment by wedobetter** [comment] 2021-09-24 22:58
this is doing for me, while I wait for a proper fix.

`  
//go:embed dist/bws/*
var angular embed.FS
.
.
.
app.Use("/", filesystem.New(filesystem.Config{
    Root: http.FS(angular),
    Browse:       true,
    PathPrefix: "/dist/bws",
    Index:        "/index.html",
    NotFoundFile: "/dist/bws/index.html",
  }))
`

**Comment by ReneWerner87** [comment] 2021-10-06 07:17
fixed with https://github.com/gofiber/fiber/pull/1547

release https://github.com/gofiber/fiber/releases/tag/v2.20.0

**Closed by ReneWerner87** 2021-10-06 07:17 UTC
Labels: ☢️ Bug
