### ISSUE TITLE
🐛 Why  custom format show default template 

### ISSUE THREAD

**Issue by liaohongxing** [gofiber/fiber#1627] opened 2021-11-18 08:50 UTC
**Fiber version**
v2.22.0
**Issue description**

custom format show default template 

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  app.Use(logger.New(logger.Config{
      Format: "${status} ${method} ${url}\n",
  }))

  log.Fatal(app.Listen(":3000"))
}
```

console output:

16:35:54 | 200 |      0s |    192.168.1.42 | GET     | /api

**Comment by ReneWerner87** [comment] 2021-11-18 09:10
Duplicate of #1625
Duplicate of #1609

**Closed by ReneWerner87** 2021-11-18 09:10 UTC
