### ISSUE TITLE
The compiled binary contains lot of test data from github.com/klauspost/compress package🐛 

### ISSUE THREAD

**Issue by adnan-kamili** [gofiber/fiber#1782] opened 2022-02-16 12:08 UTC
**Fiber version**

v2.9.0

**Issue description**

On static analysis of the binary, generated after compiling our go fiber app we found out a lot of text and links in the final binary, which turned out to be test data in the

github.com/klauspost/compress

package.

Here is how it looks in the hex editor:
<img width="1067" alt="Screenshot 2022-02-16 at 5 35 37 PM" src="https://user-images.githubusercontent.com/1573517/154261345-e9904251-4f4a-4947-b2b1-8261fe4ef07b.png">

Due to this, our customers are unable to use our software due to static analysis of the file containing a lot of unknown URLs. 
Please look into this issue urgently.

**Comment by ReneWerner87** [comment] 2022-02-16 12:33
can you see how it behaves in the new version and prepare a small reproducible example

**Comment by ReneWerner87** [comment] 2022-02-16 12:38
interesting find, think this should be created in the github repository of the package
https://github.com/klauspost/compress

think the test data should be in another folder which is not part of the package

**Comment by klauspost** [comment] 2022-02-17 09:02
The text is from `lcet10.txt` - a common benchmark file for compression. Used by snappy and my package.

It does not exist directly in the repo. Running tests will attempt to download it from `https://raw.githubusercontent.com/google/snappy/master/testdata/`. Do you invoke tests on third party packages?

I don't see this package having references to wither snappy nor my package. So how it ends up being embedded in your binary - I have no clue.

**Comment by adnan-kamili** [comment] 2022-02-17 09:46
Do you invoke tests on third party packages? 

No we don't.

**Comment by klauspost** [comment] 2022-02-17 10:11
This is the [brotli dictionary](https://github.com/nishemon/get-brotli-dictionary). From github.com/andybalholm/brotli

Seems like it has text from common benchmarks. Cheaters.

**Comment by ahmad-kemsan** [comment] 2022-02-17 10:18
Here is our go.mod file:

```
module github.com/xyz/apf

go 1.16

require (
	github.com/form3tech-oss/jwt-go v3.2.3+incompatible
	github.com/gofiber/fiber/v2 v2.9.0
	github.com/gofiber/jwt/v2 v2.2.1
	github.com/gofiber/redirect/v2 v2.1.2
	github.com/kardianos/service v1.2.0
	github.com/mergermarket/go-pkcs7 v0.0.0-20170926155232-153b18ea13c9
	github.com/rs/zerolog v1.21.0
	github.com/satori/go.uuid v1.2.0
	github.com/spf13/pflag v1.0.5
	github.com/spf13/viper v1.7.1
	github.com/stretchr/testify v1.7.0 // indirect
	gopkg.in/natefinch/lumberjack.v2 v2.0.0
)
```

**Comment by klauspost** [comment] 2022-02-17 10:23
[fasthttp](https://github.com/valyala/fasthttp/blob/master/go.mod#L6) imports it.

**Comment by ahmad-kemsan** [comment] 2022-02-17 10:24
@klauspost thanks a lot for finding this.

@ReneWerner87 can you please look into this?

**Comment by ReneWerner87** [comment] 2022-02-17 10:30
yes right the packages are packages from fasthttp 

think in the issue section of fasthttp or the brotli repository you should create a report with the findings

best with a small example to reproduce (without fiber, just with the information of the repository itself, so you can see that it is a real problem from their package)

**Comment by ReneWerner87** [comment] 2022-02-17 10:31
@ahmad-kemsan thx for https://github.com/valyala/fasthttp/issues/1220 but we should maybe also create a report in the brotli repo -> fasthttp will not be able to do much there either

**Comment by klauspost** [comment] 2022-02-17 10:36
The best the brotli package can do is obfuscate it. It needs the data to operate. Maybe a simple xor could be done, but since it is a cgo package they would probably prefer it to be done upstream.

Another alternative, is to build with [garble](https://github.com/burrowers/garble) which obfuscates static data. I use this for some of my binary releases to avoid (bad) AV software triggering on common Go runtime stuff.

**Comment by ReneWerner87** [comment] 2022-02-17 10:41
you mean the data is not only used for test or benchmark purposes ? 

if not i don't understand why you can't just move them into the folder and leave them out of the consumer package ?

**Comment by ReneWerner87** [comment] 2022-02-17 10:43
we also have various test data which we need -> these are simply hidden in the .github folder and are therefore not pulled into the package for the release

**Comment by klauspost** [comment] 2022-02-17 10:43
@ReneWerner87 It is required to decompress and usually (but not required) for compression. It is a dictionary used to reference common words, reducing the size of compressed data.

**Comment by ReneWerner87** [comment] 2022-02-17 10:43
ahh ok

but then there is also no possibility to let them out

**Comment by tomaswarynyca** [comment] 2022-02-17 15:09
@ahmad-kemsan the issues on fasthttp were closed
You have to open it in [brotli](https://github.com/andybalholm/brotli)

**Comment by ReneWerner87** [comment] 2022-03-04 07:59
brotli ticket is also closed
can we close this ? its not really related to fiber
the issue is in the named repositories

**Closed** 2022-03-07 07:20 UTC
Labels: ☢️ Bug
