### ISSUE TITLE
🐛 middleware monitor error

### ISSUE THREAD

**Issue by guolimin1995** [gofiber/fiber#903] opened 2020-10-09 10:21 UTC
**Fiber version**
v2.0.6
**Issue description**
server shutdown with errors when run wrk -t 4 -c 400 -d 20s http://localhost:8091/test:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4691427]

goroutine 34 [running]:
github.com/gofiber/fiber/v2/middleware/monitor.updateStatistics(0xc00016dc70)
	/Users/zerone/go/pkg/mod/github.com/gofiber/fiber/v2@v2.0.6/middleware/monitor/monitor.go:98 +0x127
github.com/gofiber/fiber/v2/middleware/monitor.New.func1.1(0xc00016dc70)
	/Users/zerone/go/pkg/mod/github.com/gofiber/fiber/v2@v2.0.6/middleware/monitor/monitor.go:61 +0x2b
created by github.com/gofiber/fiber/v2/middleware/monitor.New.func1
	/Users/zerone/go/pkg/mod/github.com/gofiber/fiber/v2@v2.0.6/middleware/monitor/monitor.go:59 +0xbf
exit status 2

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gofiber/fiber/v2/middleware/monitor"


func main() {
  app := fiber.New()

  // Steps to reproduce
 app.Get("/dashboard", monitor.New())
 app.Get("/test", func(c *fiber.Ctx) error {
	 return c.SendString("helloweb")
 })

  log.Fatal(app.Listen(":8091"))
}
```

**Comment by hi019** [comment] 2020-10-09 16:59
Hi :wave:

I'm unable to reproduce the issue with the same setup on Linux and using bombardier (`.\bombardier-windows-amd64.exe -c 400 -d 20s http://localhost:3000/test`) on Windows 10. 

Does this only occur during benchmarking? From first glance the issue looks to be caused by [gopsutil](https://github.com/shirou/gopsutil) which we use to collect statistics for the dashboard.

**Comment by guolimin1995** [comment] 2020-10-10 02:09
> Hi 👋
> 
> I'm unable to reproduce the issue with the same setup on Linux and using bombardier (`.\bombardier-windows-amd64.exe -c 400 -d 20s http://localhost:3000/test`) on Windows 10.
> 
> Does this only occur during benchmarking? From first glance the issue looks to be caused by [gopsutil](https://github.com/shirou/gopsutil) which we use to collect statistics for the dashboard.

i see. thanks for you reply. should i close this issue?

**Comment by hi019** [comment] 2020-10-10 02:34
It may be a one-off thing and `gopsutil` works every other time. If that's the case, #906 should fix the issue. You can wait until its merged or edit monitor.go to [this](https://github.com/gofiber/fiber/pull/906/commits/e3e833e4349ecc02a2b59681f76dcf4b486e97a2) and try to reproduce the issue again. 

If the issue still occurs, I created [this](https://gist.github.com/hi019/94d7ec2d42b888dc8e152de6e9f54917) gist which mimics what the monitor code does, but it prints the error from gopsutil if there is one.

**Comment by guolimin1995** [comment] 2020-10-10 02:47
> It may be a one-off thing and `gopsutil` works every other time. If that's the case, #906 should fix the issue. You can wait until its merged or edit middleware/monitor/monitor.go to [this](https://github.com/gofiber/fiber/pull/906/commits/e3e833e4349ecc02a2b59681f76dcf4b486e97a2) and try to reproduce the issue again.
> 
> If the issue still occurs, I created [this](https://gist.github.com/hi019/94d7ec2d42b888dc8e152de6e9f54917) gist which mimics what the monitor code does, but it prints the error from gopsutil if there is one.

OK. thanks

**Closed** 2020-10-10 14:26 UTC
Labels: Status: In Progress, Type: Bug
