### ISSUE TITLE
🐞 Nested routing not working, id interpolated incorrectly

### ISSUE THREAD

**Issue by cgiacomi** [gofiber/fiber#354] opened 2020-05-10 22:12 UTC
**Fiber version/commit**
1.9.5

**Issue description**
Nested routes not called, id interpolated incorrectly

**Expected behavior**
Nested route called correctly

**Steps to reproduce**

go run server.go
(snippet below)

curl --request GET --url http://localhost:1500/resource
(this route called correctly)

curl --request GET --url http://localhost:1500/resource/12345
(this route will work, and response contains the correct id '12345')

curl --request GET --url http://localhost:1500/resource/12345/bug
(this route will not work, 'bug' is considered part of the id of the resource, still routes to the previous route)

curl --request GET --url http://localhost:1500/resource/12345/bug/999
(also not working, will still call 'reusource/:id' with the invalid id)

**Code snippet**

```go
//server.go
package main

import "github.com/gofiber/fiber"

func main() {
	app := fiber.New()

	app.Get("/resource", func(c *fiber.Ctx) {
		c.Send("resource")
	})

	app.Get("/resource/:id", func(c *fiber.Ctx) {
		c.Send("resource - id: " + c.Params("id"))
	})

	app.Get("/resource/:id/bug", func(c *fiber.Ctx) {
		c.Send("NEVER CALLED BUG id: " + c.Params("id"))
	})

        app.Get("/resource/:id/bug/:bid", func(c *fiber.Ctx) {
		c.Send("NEVER CALLED BUG bid: " + c.Params("bid"))
	})

	app.Listen(1500)
}

```

Thank you for the great work with this framework. Bug reports are so impersonal, this one doesn't want to be like that, and it's not a show stopper for me as I reverted to 1.9.3 which seems to work fine. Thank you.

**Comment by Fenny** [comment] 2020-05-11 02:38
cc @ReneWerner87
```
   --- FAIL: Test_With_Nested_Routing_Multiple_Params/{uri:/resource/12345/bug/999_params:[12345_999]_ok:true} (0.00s)
        router_test.go:251: Path.Match() got = [], want [12345 999]
        router_test.go:254: Path.Match() got1 = false, want true
```
@cgiacomi, thanks for your bug report, I can confirm that this is unwanted behavior and will be fixed asap.

**Comment by ReneWerner87** [comment] 2020-05-11 05:59
![image](https://user-images.githubusercontent.com/7063188/81528431-f4b50600-935c-11ea-981e-08c8e4562f6e.png)
![image](https://user-images.githubusercontent.com/7063188/81528463-08606c80-935d-11ea-8e34-48adc20bbfd3.png)
![image](https://user-images.githubusercontent.com/7063188/81528473-12826b00-935d-11ea-9336-ecbc80e98b01.png)

![image](https://user-images.githubusercontent.com/7063188/81528485-1e6e2d00-935d-11ea-90ad-747ac161f5c3.png)

am currently not able to reproduce the error, if I can, I will fix the problem, does anyone see an error in the reproduction?

**Comment by cgiacomi** [comment] 2020-05-11 06:19
Hi ReneWerner87,

looking at the output from your tests you should see the response

 "NEVER CALLED BUG id: 12345" and "NEVER CALLED BUG bid: 999" returned...

but it doesn't seem to me that it's the case, which means that you just
reproduced the bug.

kind regards,

Chris

**Comment by ReneWerner87** [comment] 2020-05-11 06:20
found the bug in the meantime, I'm working on a fix

**Comment by cgiacomi** [comment] 2020-05-11 06:21
@ReneWerner87 @Fenny thank you for your time.

**Comment by ReneWerner87** [comment] 2020-05-11 06:46
fixed in PR:
https://github.com/gofiber/fiber/pull/356
fix in fastpath:
https://github.com/renanbastos93/fastpath/pull/6

@cgiacomi thanks for the bug report

**Comment by Fenny** [comment] 2020-05-11 11:44
Thanks @ReneWerner87!
@cgiacomi thnx for your report, hotfix is tagged in [v1.9.6](https://github.com/gofiber/fiber/releases/tag/v1.9.6)

**Closed by Fenny** 2020-05-11 11:44 UTC
Labels: bug, pending/investigation
