### ISSUE TITLE
🚀 EJS template renderer

### ISSUE THREAD

**Issue by SowinskiBraeden** [gofiber/fiber#1773] opened 2022-02-13 05:49 UTC
Enabling fiber to use a renderer such as EJS, for example:

```
package main

import (
  "github.com/gofiber/fiber/v2"
  "github.com/gofiber/fiber/v2/template/ejs"
)

func main() {
  app := fiber.New(fiber.Config{
        Views: ejs.New("./views", ".ejs"),
  })

  app.Post("/", func (c *fiber.Ctx) error {
    return c.Render("index", fiber.Map{
          "myVariable": someRandomVariable,
      })
  })
}
```

enabling the ability to serve a .ejs file and pass variables

**Comment by jack5341** [comment] 2022-02-19 23:54
I would like to take this issue, I can gladly develop this feature.

**Comment by SowinskiBraeden** [comment] 2022-02-20 00:07
> I would like to take this issue, I can gladly develop this feature.

I know there is the html renderer, but I really like using .ejs
I use it often and really like the simplicity of it compared to html conditional statements. So I just thought it would be great to see EJS compatibility within one of my projects.

**Comment by ReneWerner87** [comment] 2022-02-20 07:30
Ok, you are welcome to create a pull request

Please create the feature report in the template repository next time

**Comment by efectn** [comment] 2022-04-08 15:58
duplicate of https://github.com/gofiber/template/issues/164

**Closed by efectn** 2022-04-08 15:58 UTC
Labels: 👍 Accepting PR, ✏️ Feature
