### ISSUE TITLE
📝 [Proposal]: Re-introduce the DisableStartupMessage configuration option in Fiber v3

### ISSUE THREAD

**Issue by thomasvvugt** [gofiber/fiber#2972] opened 2024-04-15 19:07 UTC
### Feature Proposal Description

Would love to see the DisableStartupMessage configuration option return in Fiber v3 to silence my application test output logs.

### Alignment with Express API

Not familiar

### HTTP RFC Standards Compliance

N/A

### API Stability

N/A

### Feature Examples

```go
app := fiber.New(fiber.Config{
    // Disable startup message
    DisableStartupMessage: true,
})
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by gaby** [comment] 2024-04-16 01:16
Duplicate of https://github.com/gofiber/fiber/issues/2968

**Comment by gaby** [comment] 2024-04-16 01:20
@thomasvvugt Example:

```go
app := fiber.New()
app.Listen(":3000", ListenConfig{DisableStartupMessage: true})
```

**Closed by gaby** 2024-04-16 01:20 UTC
Labels: ✏️ Feature, v3, 📝 Proposal
