### ISSUE TITLE
🤗 [Question]: problem with Destroy Session in middleware session

### ISSUE THREAD

**Issue by mustafanass** [gofiber/fiber#2476] opened 2023-05-24 16:28 UTC
### Question Description

hi there 

when i use middleware session to store sessions its works fine but when its come to Destroy sessions i get problem function of logout dont works or execute so its dont effect and dont show any error but when pars an parameters to url (127.0.0.1:3000/logout?parameters) its works and functions execute and user logout but when re-login and use (127.0.0.1:3000/logout?same parameters above) its dont works and if change parameters to any other value its works !! my full code   as shown  :

auth.go -> logout function

```
func Logout(c *fiber.Ctx) error {
	fmt.Println("start logout function")
	if !CheckSessions(c) {
		return c.Redirect("/login", 301)
	}
	SessionsAccess, err := StorSessions.Get(c)
	if err != nil {
		fmt.Println("error in Get Sessions")
	} else {
		SessionsAccess.Destroy()
	}
	return c.Redirect("/login", 301)

}
```
base_service.go

```
var StorSessions *session.Store

func InitSessionStore() {
	StorSessions = session.New(session.Config{KeyGenerator: utils.UUIDv4})
}

func CheckSessions(c *fiber.Ctx) bool {

	SessionsAccess, err := StorSessions.Get(c)
	if err != nil {
		fmt.Println(err)
		return false
	}
	checkLogin := SessionsAccess.Get("logged")
	if checkLogin != nil && checkLogin == true {
		return true
	}
	return false
}
```

routes.go

```
package routes

import (
	"github.com/gofiber/fiber/v2"
	"urufi.com/urufi_clients/services"
)

func SetRoutes(app *fiber.App) {

	app.Get("/login", services.GetLogin)
	app.Post("/login", services.SendLogin)
	app.Get("/index", services.GetIndex)
	app.Get("/register", services.GetRegister)
	app.Post("/register", services.SendRegister)
	app.Get("/logout", services.Logout)
}
```

main.go 

```
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
	"urufi.com/urufi_clients/routes"
	"urufi.com/urufi_clients/services"
)

func main() {

	engine := html.New("./views", ".html")
	app := fiber.New(fiber.Config{
		Views:       engine,
		ViewsLayout: "layouts/main",
	})
	services.InitSessionStore()
	app.Static("/", "./static")
	routes.SetRoutes(app)
	log.Fatal(app.Listen(":3000"))

}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by mustafanass** [comment] 2023-05-24 20:06
its solved the problem in my routes 

```
	app.Get("/login", services.GetLogin)
	app.Post("/login", services.SendLogin)
	app.Get("/index", services.GetIndex)
	app.Get("/register", services.GetRegister)
	app.Post("/register", services.SendRegister)
	app.Get("/logout", services.Logout)
```
in routes of login (POST, GET) they have same name (login) and in my logout function  so i change Post routes of login to be send_login and all works fine 

```
	app.Get("/login", services.GetLogin)
	app.Post("/send_login", services.SendLogin)
	app.Get("/index", services.GetIndex)
	app.Get("/register", services.GetRegister)
	app.Post("/register", services.SendRegister)
	app.Get("/logout", services.Logout)

```

**Comment by ReneWerner87** [comment] 2023-05-26 05:58
we had a chat in discord about this problem
@mustafanass could you solve it? 
what was the cause? Caching? cookie and redirect?

Can we close the issue?

**Comment by mustafanass** [comment] 2023-05-26 06:53
Yes , its solved the problem with caching so remove cookie from browser and all works fine , thank you for your help

**Closed** 2023-05-26 06:55 UTC
Labels: 🤔 Question
