### ISSUE TITLE
🚀 Mounted app views

### ISSUE THREAD

**Issue by yekurtal** [gofiber/fiber#1276] opened 2021-04-10 11:11 UTC
**Is your feature request related to a problem?**
Yes, when mounting an app with views the views are not rendered. See #996.

**Describe the solution you'd like**
Mounted app routes use the mounted app views.

**Describe alternatives you've considered**
Setting views in main app.

**Additional context**
None?

**Comment by ReneWerner87** [comment] 2021-04-10 11:23
Can you provide a reproducible example, that would speed up troubleshooting tremendously

**Comment by ReneWerner87** [comment] 2021-04-12 06:58
@yekurtal

**Comment by yekurtal** [comment] 2021-04-12 08:45
Github didn't notify me about your first request, sorry about that.

Here is a simple mounted app with embedded template:

`/web/template/hello_world.gohtml`
`<h1>Hello {{ .Name }}!</h1>`

`/main.go`
`
//go:embed web/template/*
var template embed.FS

func main() {
	sub := fiber.New(fiber.Config{
		Views: html.NewFileSystem(tool.SubAndWrapFS(template, "web/template"), ".gohtml"),
	})

	sub.Get("/:name", func(ctx *fiber.Ctx) error {
		return ctx.Render("hello_world", fiber.Map{
			"Name": ctx.Params("name"),
		})
	})

	app := fiber.New()

	app.Mount("/hello", sub)

	if err := app.Listen("localhost:5000"); err != nil {
		log.Fatal(err)
	}
}
`

Hope this helps.

**Comment by ReneWerner87** [comment] 2021-04-14 07:10
okay we will check this

**Comment by gzuidhof** [comment] 2021-04-27 00:55
I'd like to add that I ran into the same issue/shortcoming. It seems that after an app is mounted the main app's config.Views is used.

Peeking into `app.Mount`'s implementation it looks like only the routes get copied over, does this mean that the config of the mounted app gets ignored in general? Note I may be misunderstanding!

**Comment by gzuidhof** [comment] 2021-04-27 01:42
This may be useful for you as well @yekurtal, I pulled the code from `ctx.Render` into its own small renderer:
```go
package templaterenderer

import (
	"github.com/gofiber/fiber/v2"
	"github.com/valyala/bytebufferpool"
)

type TemplateRenderer struct {
	views fiber.Views
}

func NewRenderer(v fiber.Views) TemplateRenderer {
	return TemplateRenderer{
		views: v,
	}
}

func (r *TemplateRenderer) Render(ctx *fiber.Ctx, name string, bind interface{}, layouts ...string) error {
	buf := bytebufferpool.Get()
	defer bytebufferpool.Put(buf)

	err := r.views.Render(buf, name, bind, layouts...)
	if err != nil {
		return err
	}

	resp := ctx.Response()
	// Set Content-Type to text/html
	resp.Header.SetContentType(fiber.MIMETextHTMLCharsetUTF8)
	// Set rendered template to body
	resp.SetBody(buf.Bytes())

	return nil
}
```

For my own usecase I need the template engine to be separate for mounted apps (i.e. them sharing the same globals would be problematic), this does the trick for now :)

**Comment by ReneWerner87** [comment] 2021-06-13 10:34
@yekurtal yes right we currently only copy the routes and the reference to the other app is lost

feel free to implement a fix for this, pull requests are always welcome

as long as I would recommend you to set the configuration of the fiber app in both apps
```go
func main() {
    config := fiber.Config{
        Views: html.NewFileSystem(SubAndWrapFS(template, "web/template"), ".gohtml"),
    }

    sub := fiber.New(config)
    sub.Get("/:name", func(ctx *fiber.Ctx) error {
        return ctx.Render("hello_world", fiber.Map{
            "Name": ctx.Params("name"),
        })
    })

    app := fiber.New(config)
    app.Mount("/hello", sub)

    log.Fatalln(app.Listen("localhost:5000"))
}
```


@fenny what do you mean ?

**Comment by efectn** [comment] 2021-10-11 12:43
I'm interested in this issue. Probably i'll create PR on weekend. Can you assigne me @ReneWerner87?

**Closed** 2022-02-06 13:58 UTC
Labels: ♻ Wait for Response, 👍 Accepting PR
