### ISSUE TITLE
🐛 [Bug]: Adaptor middleware duplicates cookies

### ISSUE THREAD

**Issue by DreamwareDevelopment** [gofiber/fiber#3089] opened 2024-07-24 19:05 UTC
### Bug Description

I proved that the middleware is duplicating cookies in the cookie header, I have a fix that worked for me.

### How to Reproduce

1. Use cookies (I used supertokens.Middleware as the argument to adaptor.HTTPMiddleware() which sets cookies)

### Expected Behavior

Cookies should not be duplicated within the header.

### Fiber Version

v2.52.4

### Code Snippet (optional)

```go
Here is the fix:

func HTTPMiddleware(mw func(http.Handler) http.Handler) fiber.Handler {
	return func(c fiber.Ctx) error {
		var next bool
		nextHandler := http.HandlerFunc(func(_ http.ResponseWriter, r *http.Request) {
			// Convert again in case request may modify by middleware
			next = true
			c.Request().Header.SetMethod(r.Method)
			c.Request().SetRequestURI(r.RequestURI)
			c.Request().SetHost(r.Host)
			c.Request().Header.SetHost(r.Host)

			for key, val := range r.Header {
				if key == "Cookie" {
					// Handle Cookie header separately to avoid duplicates
					c.Request().Header.Del(key)
					c.Request().Header.Set(key, strings.Join(val, "; "))
				} else {
					for _, v := range val {
						c.Request().Header.Set(key, v)
					}
				}
			}
			CopyContextToFiberContext(r.Context(), c.Context())
		})

		if err := HTTPHandler(mw(nextHandler))(c); err != nil {
			return err
		}

		if next {
			return c.Next()
		}
		return nil
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment] 2024-07-24 23:55
@DreamwareDevelopment The middleware is not duplicating cookies, you are sending the cookie as a header.

Please provide an example of how you are using Adaptor with SuperToken.

**Comment by DreamwareDevelopment** [comment] 2024-07-28 04:11
```app.Use(adaptor.HTTPMiddleware(supertokens.Middleware))```

**Comment by gaby** [comment] 2024-07-28 04:12
@DreamwareDevelopment We need a full example to be able to replicate/debug

**Comment by DreamwareDevelopment** [comment] 2024-07-29 00:47
Sorry, I'm a solo founder and I don't have time to do a base example. But here's the final code that fixed my issue for the middleware adaptor:

```
func HTTPMiddleware(mw func(http.Handler) http.Handler) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var next bool
		nextHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			next = true
			// Convert again in case request may modify by middleware
			c.Request().Header.Reset()
			c.Request().Header.SetMethod(r.Method)
			c.Request().SetRequestURI(r.RequestURI)
			c.Request().SetHost(r.Host)
			c.Request().Header.SetHost(r.Host)
			// Handle Cookie header separately
			if cookies := r.Header.Get("Cookie"); cookies != "" {
				c.Request().Header.Set("Cookie", cookies)
			}

			// Set other headers
			for key, val := range r.Header {
				if key != "Cookie" {
					for _, v := range val {
						c.Request().Header.Set(key, v)
					}
				}
			}
			adaptor.CopyContextToFiberContext(r.Context(), c.Context())
		})

		if err := adaptor.HTTPHandler(mw(nextHandler))(c); err != nil {
			return err
		}

		if next {
			return c.Next()
		}
		return nil
	}
}
```

To note here is that I'm clearing the fiber headers before writing to them, then cookies are being set with the value in the http request header.

**Comment by haikalSusanto** [comment] 2024-08-10 15:34
Hello, sorry to jump in, after reading the code I managed to reproduce this particular issue through unit test and some printing with fmt package.

I modify this handler and test in function `Test_HTTPMiddleware` to investigate what happened

original:
https://github.com/gofiber/fiber/blob/e43763311d894a2de777c4d116bfd97a1bf00a17/middleware/adaptor/adaptor_test.go#L163-L181

modified: 
```
	app.Post("/", func(c fiber.Ctx) error {
		fmt.Println("Start of request handler: ", c.GetReqHeaders())
		value := c.Context().Value(TestContextKey)
		val, ok := value.(string)
		if !ok {
			t.Error("unexpected error on type-assertion")
		}
		if value != nil {
			c.Set("context_okay", val)
		}
		value = c.Context().Value(TestContextSecondKey)
		if value != nil {
			val, ok := value.(string)
			if !ok {
				t.Error("unexpected error on type-assertion")
			}
			c.Set("context_second_okay", val)
		}

		// RETURNING CURRENT COOKIES TO RESPONSE
		var cookies []string = strings.Split(c.Get("Cookie"), "; ")
		for _, cookie := range cookies {
			c.Set("Set-Cookie", cookie)
		}

		fmt.Println("End of request handler: ", c.GetReqHeaders())
		return c.SendStatus(fiber.StatusOK)
	})
```
modified test
```
	req, err := http.NewRequestWithContext(context.Background(), fiber.MethodPost, "/", nil)
	req.Host = expectedHost
	req.AddCookie(&http.Cookie{Name: "cookieOne", Value: "valueCookieOne"})
	req.AddCookie(&http.Cookie{Name: "cookieTwo", Value: "valueCookieTwo"})
	require.NoError(t, err)

	resp, err := app.Test(req)
	require.NoError(t, err)
	require.Len(t, resp.Cookies(), 2)
	require.Equal(t, "okay", resp.Header.Get("context_okay"))
	require.Equal(t, "okay", resp.Header.Get("context_second_okay"))
```

the result cookie is duplicating in a weird way like this below. 
```
 Error:          "[cookieOne=valueCookieOne cookieTwo=valueCookieTwo 0ookieOne=valueCookieOne cookieTwo=valueCookieTwo]" should have 2 item(s), but has 4
 ```

i found out that, when it comes to value with type of array

https://github.com/gofiber/fiber/blob/e43763311d894a2de777c4d116bfd97a1bf00a17/middleware/adaptor/adaptor.go#L99-L103

the setter of Header is not replacing existing Header but instead appending it. this is the existing behavior in fasthttp.

i suggest that, for type array, we need to do some checking if there is any difference first before we use the setter. if this suggestion is okay then ill help to make the solution for this, or maybe there is a better way?

peace 😁

**Comment by gaby** [comment] 2024-08-10 15:36
@haikalSusanto Thanks, I will investigate today.

**Comment by haikalSusanto** [comment] 2024-08-22 18:39
Any update on this?

**Comment by sigmundxia** [comment] 2024-09-11 09:03
If my check was correct, the problem might be caused by upstream [fasthttp](https://github.com/valyala/fasthttp), I've filed an issue there :)

**Comment by sigmundxia** [comment] 2024-09-26 02:40
This issue actually deals with two problems: duplication of cookies, and the strange `0ookieOne` that appeared in @haikalSusanto's test.

The latter problem was a bug in fasthttp that has been fixed by [this pull request](https://github.com/valyala/fasthttp/pull/1860) and merged into version [v1.56.0](https://github.com/valyala/fasthttp/releases/tag/v1.56.0), so the issue should be resolved 😊

Regarding the former problem, after the discussion of [this pull request](https://github.com/valyala/fasthttp/pull/1864), `header.Set` keeping the original features (not deleting the original cookies) was considered a better solution. Therefore, I submitted a pull request to try to fix this issue in gofiber and add the corresponding tests, hopefully this will be useful in solving this problem 😊

**Comment by franciscoescher** [comment] 2024-09-30 13:34
using fasthttp v1.56.0 does not fix the issue for me

**Closed** 2024-10-03 14:19 UTC
Labels: ☢️ Bug, 👍 Accepting PR
