### ISSUE TITLE
🔥 Pass data to next handler.

### ISSUE THREAD

**Issue by Nifty255** [gofiber/fiber#332] opened 2020-04-30 23:40 UTC
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Implement a lazily-allocated map into Ctx, which can be given data via a `Pass` function or retrieved from via `Retrieve` function. There may be a better idea, though. If there is, go for it.

**Describe alternatives you've considered**
I've considered writing a global map for the passing of data, but it would have to be mutexed, and any final handlers wouldn't know which data belongs to it, since no Ctx-specific request ID exists either. Channels can't be used either since they can't exist within or be told about from within the scope of the Ctx.

**Additional context**
Both Express and Ruby on Rails provide the ability to declare middleware or middleware-like code which can pass data to a final handler. For example, in Express:
```javascript
app.use("/*", (req, res, next) => {
  req.user = userByToken(req.query.token);
});
app.get("/messages", (req, res) => {
  var messages = dbGetMessages(req.user);
  res.json(messages);
});
```
Such a feature in Fiber would allow for more compact code, as each final handler wouldn't have to obtain its relevant user, potentially across hundreds of handlers.

Side note: I tried joining the Discord, but the #rules channel wouldn't display any message to react to as the bot requests.

**Comment by thomasvvugt** [comment] 2020-05-01 08:18
Duplicate of #158

**Closed by thomasvvugt** 2020-05-01 08:18 UTC
Labels: enhancement

**Comment by Nifty255** [comment] 2020-05-01 08:20
Perhaps a more present example in the readme or documentation would be helpful?

**Comment by thomasvvugt** [comment] 2020-05-01 08:24
Hi @Nifty255 ,
You can create a PR in [gofiber/recipes](https://github.com/gofiber/recipes) if you like.
Documentation for Locals can be found [here](https://docs.gofiber.io/context#locals).
Thanks for bringing this up!
