### ISSUE TITLE
C.JSON not work on go 1.18

### ISSUE THREAD

**Issue by luyouxin84** [gofiber/fiber#1820] opened 2022-03-17 06:34 UTC
in go 1.17.8 c.json work fine,but after i upgrade go version , c.json not work report "runtime error empty pointer"

**Comment by efectn** [comment] 2022-03-17 09:10
Can you send issue to https://github.com/goccy/go-json

**Comment by limjinyung** [comment] 2022-03-17 09:12
same here, but I get `unexpected fault address` instead

**Comment by efectn** [comment] 2022-03-17 13:05
Sorry 😅😅

**Comment by efectn** [comment] 2022-03-18 10:20
@luyouxin84 @limjinyung What version of fiber are you using?

**Comment by luyouxin84** [comment] 2022-03-18 10:32
> @luyouxin84 @limjinyung What version of fiber are you using?

github.com/gofiber/fiber/v2 v2.23.0

**Comment by efectn** [comment] 2022-03-18 10:40
> > @luyouxin84 @limjinyung What version of fiber are you using?
> 
> github.com/gofiber/fiber/v2 v2.23.0

Update version. It will be solved probably. Also i recommend you use latest version of Fiber. They include most bug fixes and features.

**Comment by kokizzu** [comment] 2022-03-21 06:52
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1061610/159216122-0535aded-58c0-43e8-8af9-5e36376a6444.png">

**Comment by efectn** [comment] 2022-03-21 07:09
> > > @luyouxin84 @limjinyung What version of fiber are you using?
> > 
> > 
> > github.com/gofiber/fiber/v2 v2.23.0
> 
> Update version. It will be solved probably. Also i recommend everybody to use latest version of Fiber. They include most bug fixes and features.

I'm closing the issue because of this. If you problem not solved, re-open the issue.

**Comment by luisgarciaalanis** [comment] 2022-03-24 06:38
I  am seeing this crash on v2.30.0

the JSON encoder is crashing.
github.com/gofiber/fiber/v2/internal/go-json/encoder.copyOpcode(0x0)
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/opcode.go:322 +0x33
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).linkRecursiveCode(0xc00016f3b0?, 0xc0002cb950)
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:892 +0x13c
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).codeToOpcode(0x0?, 0xc0002cb950, 0x1617c80, {0x17b2320?, 0xc00016f3b0?})
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:883 +0xe5
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).codeToOpcodeSet(0x8?, 0x1617c80, {0x17b2320?, 0xc00016f3b0})
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:108 +0xc9
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).compile(0x8?, 0x1617c80)
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:104 +0x54
github.com/gofiber/fiber/v2/internal/go-json/encoder.CompileToGetCodeSet(0xc00061d488?, 0x107a08c?)
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler_norace.go:18 +0x125
github.com/gofiber/fiber/v2/internal/go-json.encode(0xc000112820, {0x1617c80, 0xc00016f380})
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encode.go:224 +0xd0
github.com/gofiber/fiber/v2/internal/go-json.marshal({0x1617c80, 0xc00016f380}, {0x0, 0x0, 0x30?})
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encode.go:148 +0xba
github.com/gofiber/fiber/v2/internal/go-json.MarshalWithOption(...)
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/json.go:186
github.com/gofiber/fiber/v2/internal/go-json.Marshal({0x1617c80?, 0xc00016f380?})
        /Users/luis/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/json.go:171 +0x2a
github.com/gofiber/fiber/v2.(*Ctx).JSON(0xc0000222c0, {0x1617c80?, 0xc00016f380?})

**Comment by kokizzu** [comment] 2022-03-24 07:10
what's the payload that causes that?

**Comment by kokizzu** [comment] 2022-03-25 05:25
confirmed
```

github.com/gofiber/fiber/v2/internal/go-json/encoder.copyOpcode(0x0)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/opcode.go:322 +0x4a
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).linkRecursiveCode(0xc0000c0098, 0xc0000c6690)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:892 +0x135
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).codeToOpcode(0xc0000c0098, 0xc0000c6690, 0x91b1a0, {0x9b1668, 0xc0000c6450})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:883 +0xb1
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).codeToOpcodeSet(0xc0000c0098, 0x91b1a0, {0x9b1668, 0xc0000c6450})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:108 +0x196
github.com/gofiber/fiber/v2/internal/go-json/encoder.(*Compiler).compile(0xc0000c0098, 0x91b1a0)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler.go:104 +0x12f
github.com/gofiber/fiber/v2/internal/go-json/encoder.CompileToGetCodeSet(0xc0000e6750, 0x91b1a0)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encoder/compiler_norace.go:18 +0x25b
github.com/gofiber/fiber/v2/internal/go-json.encode(0xc0000e6750, {0x91b1a0, 0xc0000e4150})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encode.go:224 +0xed
github.com/gofiber/fiber/v2/internal/go-json.marshal({0x91b1a0, 0xc0000e4150}, {0x0, 0x0, 0x0})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/encode.go:148 +0x189
github.com/gofiber/fiber/v2/internal/go-json.MarshalWithOption({0x91b1a0, 0xc0000e4150}, {0x0, 0x0, 0x0})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/json.go:186 +0xa5
github.com/gofiber/fiber/v2/internal/go-json.Marshal({0x91b1a0, 0xc0000e4150})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/internal/go-json/json.go:171 +0x7c
github.com/gofiber/fiber/v2.(*Ctx).JSON(0xc0000de000, {0x91b1a0, 0xc0000e4150})
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/ctx.go:695 +0x87
main.main.func1(0xc0000de000)
        /home/kyz/go/src/fibercrashexample/a.go:46 +0x18c
github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc0000de000)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:132 +0x39a
github.com/gofiber/fiber/v2.(*App).handler(0xc0000001e0, 0xc0000d0000)
        /home/kyz/go/pkg/mod/github.com/gofiber/fiber/v2@v2.30.0/router.go:160 +0x91
github.com/valyala/fasthttp.(*Server).serveConn(0xc00013e480, {0x9b2318, 0xc0000c0008})
        /home/kyz/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1612
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000128c80, 0xc0000ce000)
        /home/kyz/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xe7
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        /home/kyz/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x47
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/kyz/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:195 +0x2d1
```

**Comment by kokizzu** [comment] 2022-03-25 05:29
anonymous struct is the culprit
https://github.com/goccy/go-json/issues/339

**Comment by hi019** [comment] 2022-03-25 17:53
As a workaround, you can set `JSONEncoder` in `fiber.Config` to `json.Marshal` from the stdlib.

**Comment by shahriar350** [comment] 2022-03-25 20:10
Same problem i already faced in my project and change gofiber default json to ffjson.

**Comment by luisgarciaalanis** [comment] 2022-03-28 06:09
fiber.New(fiber.Config{
		JSONEncoder: json.Marshal,
	})

Tried this and still crashes

**Comment by ReneWerner87** [comment] 2022-04-05 06:57
@luisgarciaalanis can you test it with the version 2.31.0 or the current master commit
```go
require github.com/gofiber/fiber/v2 v2.31.1-0.20220405064022-a8f9d4acfb2c
```

**Closed** 2022-04-13 08:45 UTC
Labels: ☢️ Bug, 🔍 Under Investigation

**Comment by coreybutler** [comment] 2022-04-17 00:15
I ran into this issue using 2.30.0. Upgrading to 2.31.0 resolved the issue.
