### ISSUE TITLE
🐛 [Sessions] pq: invalid byte sequence for encoding "UTF8": 0xff

### ISSUE THREAD

**Issue by hugmouse** [gofiber/fiber#1258] opened 2021-04-02 13:40 UTC
**Fiber version**

`Fiber v2.7.1`

**Postgres version**
`PostgreSQL 13.2`

**Issue description**

For some reason, when I try to save data to middleware, there is an error related to UTF8.

**Code snippet**

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/postgres"
)

func main() {
	store := session.New(session.Config{
		Storage: postgres.New(postgres.Config{
			Host:     "localhost",
			Username: "postgres",
			Password: "password",
			Database: "postgres",
		}),
	})
	app := fiber.New()

	app.Get("/set", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}
		sess.Set("key", "val")
		if err := sess.Save(); err != nil {
			panic(err)
		}
		return c.Status(fiber.StatusOK).SendString("ok")
	})

	app.Listen(":3000")
}
```

**Comment by ReneWerner87** [comment] 2021-04-03 05:37
Your report is very unusual, usually you create an issie first when you are sure and can give others the possibility to work on the bug.

Please add a reproducible example and/or information about the bug, otherwise this offers no possibility to do anything here and we have to close it.

**Comment by ReneWerner87** [comment] 2021-04-04 05:35
As I mentioned, we are closing the ticket, if you have a reproducible example and an error message, feel free to open it again

**Comment by hugmouse** [comment] 2021-04-04 08:42
Okay, the server started up after I deleted the table with the sessions, which is created by Fiber middleware package that uses Postgres.

But now a new error: `pq: invalid byte sequence for encoding "UTF8": 0xff`. haha. I'm going to keep digging, so far I haven't been able to make a repeatable error.

**Comment by hugmouse** [comment] 2021-04-04 09:15
Okay I was finally able to make a somewhat reproducible example!

**How to**
Use this code snippet and replace `postgres.Config` with your postgres database details.
Then `go run` this snippet and go to `http://localhost:3000/set`

**Code snippet**:
```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/postgres"
)

func main() {
	store := session.New(session.Config{
		Storage: postgres.New(postgres.Config{
			Host:     "localhost",
			Username: "postgres",
			Password: "password",
			Database: "postgres",
		}),
	})
	app := fiber.New()

	app.Get("/set", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}
		sess.Set("key", "val")
		if err := sess.Save(); err != nil {
			panic(err)
		}
		return c.Status(fiber.StatusOK).SendString("ok")
	})

	app.Listen(":3000")
}
```

**Log**:

```

panic: pq: invalid byte sequence for encoding "UTF8": 0xff

goroutine 22 [running]:
main.main.func1(0xc0000ce2c0, 0xc00009c4a0, 0x4)
        /home/mysh/go/src/fiberPostgres/main.go:28 +0x186
github.com/gofiber/fiber/v2.(*App).next(0xc000138500, 0xc0000ce2c0, 0xc0000ce2c0, 0xc00fafb10c, 0xfafb10c00000230)
        /home/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.7.1/router.go:126 +0x1ab
github.com/gofiber/fiber/v2.(*App).handler(0xc000138500, 0xc0000d0000)
        /home/mysh/go/pkg/mod/github.com/gofiber/fiber/v2@v2.7.1/router.go:154 +0x11a
github.com/valyala/fasthttp.(*Server).serveConn(0xc000121680, 0x8b68f8, 0xc000096028, 0x0, 0x0)
        /home/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/server.go:2168 +0x11cc
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00010efa0, 0xc0000b87e0)
        /home/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:223 +0xba
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc00010efa0, 0xc0000b87e0, 0x7b12a0, 0xc0000b87e0)
        /home/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/mysh/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:194 +0x11f
exit status 2
```

**Comment by hugmouse** [comment] 2021-04-04 09:17
btw can't reopen the Issue myself, @ReneWerner87

**Comment by hi019** [comment] 2021-04-04 15:19
I've ran your code with my database credentials and I got the `ok` response. What if you create a new database instead of using the default one, `postgres`?

**Comment by hugmouse** [comment] 2021-04-05 02:08
> I've ran your code with my database credentials and I got the `ok` response. What if you create a new database instead of using the default one, `postgres`?

Made a new db, ran the same code and I got the same error. Also tried another machine -- Windows + Postgres, I got the same result.

I wonder what might be different between our configurations that we get different results :thinking:

**Comment by hugmouse** [comment] 2021-04-05 03:06
Tried renting a VPS. Took Debian 10.9.0, installed Postgres, then Golang and tried to use my code. Got the same error.

Go: `go version go1.15.9 linux/amd64`
Postgres: `psql (PostgreSQL) 11.11 (Debian 11.11-0+deb10u1)`

**Comment by hi019** [comment] 2021-04-08 00:32
Thanks for the info, will use a VPS to try to solve this issue tomorrow.

**Comment by puuuuh** [comment] 2021-04-11 15:47
Thats because you try to store some blob data in TEXT column. Use BLOB column type and remove cast to string in
https://github.com/gofiber/storage/blob/main/postgres/postgres.go

**Comment by ReneWerner87** [comment] 2021-04-11 16:24
oh, you are right

https://stackoverflow.com/questions/1942586/comparison-of-database-column-types-in-mysql-postgresql-and-sqlite-cross-map

https://stackoverflow.com/questions/53251572/golang-postgres-storing-gob-data

hmm, we should use a blob type in our storages
```go
func (s *Storage) Set(key string, val []byte, exp time.Duration) error {
```
since we take bytes everywhere and don't know exactly if that includes utf8 we should try to use a binary/blob/byte type everywhere

@hi019 could you create a PR for this change

**Comment by hi019** [comment] 2021-04-11 16:30
Nice find @puuuuh . I'll make a PR.

**Closed** 2021-05-06 01:17 UTC
Labels: ☢️ Bug
