### ISSUE TITLE
 Prefork causing address binding problem

### ISSUE THREAD

**Issue by sarwat-osman** [gofiber/fiber#1161] opened 2021-02-09 17:48 UTC
I am doing a project using fiber v2. In server3.go, I have set "prefork: true" in my fiber config. 

**Code snippet** _from Server3.go_
```go
app := fiber.New(fiber.Config{
        Prefork: true,
        ServerHeader: "Fiber",
})

app.Static("/", "/", fiber.Static{
        Compress:      true,
        Browse: true,
        CacheDuration: 10 * time.Second,
        MaxAge:        3600,
 })

cer, err := tls.LoadX509KeyPair("ssl/nginx_bundle_193a8be386d0.crt", "ssl/private.key")
    if err != nil {
        log.Fatal(err)
    }

 config := &tls.Config{Certificates: []tls.Certificate{cer}}
 ln, err := tls.Listen("tcp", ":123", config)
 if err != nil {
        panic(err)
}
    
log.Fatal(app.Listener(ln))
```

**But running the server3.go file throws up the following error:**

```go
panic: listen tcp :123: bind: address already in use

goroutine 1 [running]:
main.main()
        /var/www/html/goimageserver/server3.go:89 +0x4fd
2021/02/09 11:12:01 exit status 2
exit status 1
```

**What I understand is that prefork spawns multiple Go processes listening on the same port. So it shows that the port is already in use by other process. But how can I actually use prefork and multiple processes listening on the same port?**

Moreover, applying this command : 
```
sudo lsof -i:123
```
doesn't even show anything, which means the port is not already in use.

**Comment by ReneWerner87** [comment] 2021-02-09 22:27
Thanks for the report, can you please give us more information about the environment

What OS/version and shell are you using?
What fiber version are you using?

With this information we then try to find the cause

**Comment by sarwat-osman** [comment] 2021-02-10 06:38
> Thanks for the report, can you please give us more information about the environment
> 
> What OS/version and shell are you using?
> What fiber version are you using?
> 
> With this information we then try to find the cause

**Comment by sarwat-osman** [comment] 2021-02-10 06:40
> Thanks for the report, can you please give us more information about the environment
> 
> What OS/version and shell are you using?
> What fiber version are you using?
> 
> With this information we then try to find the cause

OS - Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-65-generic x86_64)
Shell - GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Fiber - v2.5.0

**Comment by ReneWerner87** [comment] 2021-02-11 09:06
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
	"net"
	"time"
)


func main() {
	app := fiber.New(fiber.Config{
		Prefork: true,
		ServerHeader: "Fiber",
	})

	app.Static("/", "/", fiber.Static{
		Compress:      true,
		Browse: true,
		CacheDuration: 10 * time.Second,
		MaxAge:        3600,
	})

	ln, err := net.Listen("tcp", ":3032")
	if err != nil {
		panic(err)
	}

	log.Fatal(app.Listener(ln))
}
```

can you try it without tls so we can narrow down the error

**Comment by ReneWerner87** [comment] 2021-02-11 09:07
this is working on my mac 
![image](https://user-images.githubusercontent.com/7063188/107617838-e29c2700-6c50-11eb-9afe-1aa8fb7e1964.png)

**Comment by ReneWerner87** [comment] 2021-02-11 09:23
![image](https://user-images.githubusercontent.com/7063188/107618991-ba152c80-6c52-11eb-8601-cba270a6c1cf.png)
now i have tested it with tls and it works

i think it is because of the chosen port, please choose for testing a port which is not reserved, best one over 3000

for example: 3333

**Comment by ReneWerner87** [comment] 2021-02-11 09:29
should not be a real error, must be a used port, all variants of the prefork i have tested have worked cleanly

**Comment by ReneWerner87** [comment] 2021-02-12 07:43
i am closing the issue, if there are any other findings, it can be easily reopened

**Closed by ReneWerner87** 2021-02-12 07:43 UTC
Labels: ♻ Wait for Response

**Comment by sarwat-osman** [comment] 2021-02-13 09:44
I've tried using 3023/3333, but no change.
![go-prefork](https://user-images.githubusercontent.com/71967251/107846920-d3180c00-6e11-11eb-8f59-0fed66146855.PNG)
Can it be because of my OS environment variable where address/port reuse is disabled. But I think I've read somewhere that Fiber takes care of that on its own. Then what am I missing here?

**Comment by ReneWerner87** [comment] 2021-02-13 09:51
> address/port reuse is disabled
may be, can you please test this, unfortunately I did not get your error reproduced, so can't help you there, something must be special about your operating system/configuration

I would suggest that you test it on another machine with the same OS or revert the adjustments that could lead to this error on your operating system.

**Comment by kooohei** [comment] 2021-04-09 02:53
I have same progrem.

using 
Ubuntu:20.04
go        :1.15.6
fiber     :2.7.1

https://github.com/gofiber/recipes/tree/master/https-tls

**Comment by joyride9999** [comment] 2022-03-04 14:59
Also have the same problem:
using ubuntu 20.04.2 LTS in vbox on host win10 
go 1.17
fiber 2.20.1

**Comment by Iscalej** [comment] 2024-09-28 15:16
**Change**:  
// Create tls certificate  
cer, err := tls.LoadX509KeyPair("certs/ssl.cert", "certs/ssl.key")  
if err != nil {  
 log.Fatal(err)  
}

config := &tls.Config{Certificates: \[\]tls.Certificate{cer}}

// Create custom listener  
ln, err := tls.Listen("tcp", ":443", config)  
if err != nil {  
 panic(err)  
}

// Start server with https/ssl enabled on http://localhost:443  
log.Fatal(app.Listener(ln))  
  
**By**:  
app.ListenTLS(":443", "certs/ssl.cert", "certs/ssl.key");  
  
And Prefork should work with SSL

**Comment by meytrix183** [comment] 2024-11-22 13:40
I had a similar problem using docker when stopped using a root user and started using a "normal" user. The CGO_ENABLED=0 helped and going from ENTRYPOINT to CMD ["/bin/sh","-c","/app"] too. But again, in docker. Try with CGO_ENABLED=0.
