### ISSUE TITLE
🐛 Memory Session Storage error with string of random length

### ISSUE THREAD

**Issue by chrigeeel** [gofiber/fiber#1419] opened 2021-07-01 15:52 UTC
**Fiber version**
2.12.0

**Issue description**
When using the default memory storage as a session storage, and using sess.Set() with a key and a string of different lengths, the session handling stops working with errors such as `Unexpected EOF`.
In the below example, the key "randomStr" is set to a string with a random length on page refresh.
If you do that from two sessions (browser), you can reproduce the error after a few refreshes.
I attached a video for clarification.
This bug doesn't happen when using a DB as a storage, e.g. Redis or Mongo.

https://user-images.githubusercontent.com/76595857/124153801-1e674a00-da95-11eb-9b8c-c8e24e06e617.mp4

**Code snippet**

```go
package main

import (
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
)

var Store = session.New()

func main() {
	app := fiber.New()
	app.Get("/", handleExample)
	app.Listen(":3000")
}

func handleExample(c *fiber.Ctx) error {
	sess, err := Store.Get(c)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": err.Error(),
		})
	}
	randomStr, err := GenerateRandomString(GenerateRandomInt(10,20))
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": err.Error(),
		})
	}
	fmt.Println("random string: " + randomStr)
	defer sess.Save()
	sess.Set("randomStr", randomStr)
	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"randomStr": randomStr,
	})
}

func GenerateRandomInt(min, max int) int {
	max++
	bg := big.NewInt(int64(max - min))

	n, err := rand.Int(rand.Reader, bg)
	if err != nil {
		panic(err)
	}

	return int(n.Int64() + int64(min))
}

func GenerateRandomString(n int) (string, error) {
	const letters = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
	ret := make([]byte, n)
	for i := 0; i < n; i++ {
		num, err := rand.Int(rand.Reader, big.NewInt(int64(len(letters))))
		if err != nil {
			return "", err
		}
		ret[i] = letters[num.Int64()]
	}

	return string(ret), nil
}
```

**Comment by Spedoske** [comment] 2021-07-07 08:56
The reason for the problem is the reuse of old session byte buffer.

``` go
func releaseSession(s *Session) {
        ...
	if s.byteBuffer != nil {
		s.byteBuffer.Reset()
	}
        ...
}
```

`byteBuffer.Reset()` does not set `Buffer.buf` to `nil`, instead, it set `Buffer.buf` to a slice that has the length of 0, which do not change the array the slice points to.

```go
func (s *Session) Save() error {
        ...
	encCache := gob.NewEncoder(s.byteBuffer)
	err := encCache.Encode(&s.data.Data)
	if err != nil {
		return err
	}

	// pass raw bytes with session id to provider
	if err := s.config.Storage.Set(s.id, s.byteBuffer.Bytes(), s.exp); err != nil {
		return err
	}
        ...
}
```

```go
func acquireSession() *Session {
	s := sessionPool.Get().(*Session)
	if s.data == nil {
		s.data = acquireData()
	}
	if s.byteBuffer == nil {
		s.byteBuffer = new(bytes.Buffer)
	}
	s.fresh = true
	return s
}
```

We may reuse `byteBuffer`, which is possible because we only reset the `byteBuffer` instead of setting `byteBuffer` to nil when we `releaseSession`.
This is dangerous, because the data in the old `byteBuffer` has already used in the `map[string] interface{}` as the value of some session.
When we run `encCache.Encode(&s.data.Data)`, we actually overwrite the data in the original array which owns the old session value.

Let's take an example.
+ A session has put into the map. Key: 1, Value: `type: string, length: 5, value: Alice`.
+ The text in the `Buffer` is `type: string, length: 5, value: Alice`
+ The session has been released after `Save`, the session has been put into `session pool`.
+ During the `releaseSession`, `Buffer` has been set to  a slice whose length is 0, pointing to the array, whose value is `type: string, length: 5, value: Alice`
+ Another user comes, fiber acquire the session from the pool.
+ Another session has put into the map. Key: 2, Value: `type: string, length: 3, value: Bob`.
+ During the process of `Save`, when fiber runs `encCache.Encode(&s.data.Data)`, `Buffer` has been set to  a slice whose length is `len("type: string, length: 3, value: Bob")`, the array that buffer points to has been changed into `type: string, length: 3, value: Bobce`.
+ Therefore, the value of first session becomes `type: string, length: 3, value: Bobce`.

Therefore, for the first session, the value of session has changed during the process of `Save()`.

When the length of new string is larger than the old string, `gob` can not decode the string because of the unmatched  string length, thus causing `Unexpected EOF`.

**Comment by ReneWerner87** [comment] 2021-07-11 10:37
@chrigeeel could you test it again with commit https://github.com/gofiber/fiber/commit/cd802dfeadcf2579123eafe5b680fdad1bc0a5f7
`cd802dfeadcf2579123eafe5b680fdad1bc0a5f7`

https://jfrog.com/blog/go-big-with-pseudo-versions-and-gocenter/

**Comment by chrigeeel** [comment] 2021-07-11 10:56
> @chrigeeel could you test it again with commit [cd802df](https://github.com/gofiber/fiber/commit/cd802dfeadcf2579123eafe5b680fdad1bc0a5f7)
> `cd802dfeadcf2579123eafe5b680fdad1bc0a5f7`
> 
> https://jfrog.com/blog/go-big-with-pseudo-versions-and-gocenter/

Everything working fine for me with that version.
Thanks a lot, great!

**Comment by ReneWerner87** [comment] 2021-07-11 11:08
thx for testing and thx again for the fix @Spedoske 

in a few days we will release, then the version will be available, since there is no other task here, i would close the issue

**Closed by ReneWerner87** 2021-07-11 11:08 UTC
Labels: SessionMW, ☢️ Bug, 💡 Help wanted
