### ISSUE TITLE
🐛 dot problem with params in routes

### ISSUE THREAD

**Issue by mhf-ir** [gofiber/fiber#722] opened 2020-08-14 12:18 UTC
**Fiber version**

```
github.com/gofiber/fiber v1.13.3
```

**Issue description**

```
Params in route not worked
```

**Code snippet**

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber"
)

func main() {

	app := fiber.New()

	grp := app.Group("/.well-known/test", func(c *fiber.Ctx) {
		c.Next()
	})

	grp.Get("/", func(c *fiber.Ctx) { // work
		c.Send("Hello, World 👋!")
	})

	grp.Get("/ok", func(c *fiber.Ctx) { // work
		c.Send("OK")
	})

	grp.Get("/js/:name", func(c *fiber.Ctx) { // NOT WORK
		msg := fmt.Sprintf("Hello, %s 👋!", c.Params("name"))
		c.Send(msg) // => Hello john 👋!
	})

	app.Listen(3000)
}

```

**Comment by mhf-ir** [comment] 2020-08-14 12:20
changing
```go
	grp := app.Group("/.well-known/test", func(c *fiber.Ctx) {
		c.Next()
	})
```
to 
```go
	grp := app.Group("/well-known/test", func(c *fiber.Ctx) {
		c.Next()
	})
```

Will work

**Comment by ReneWerner87** [comment] 2020-08-14 12:40
solved with PR https://github.com/gofiber/fiber/pull/715

will be included in the next release

at the heart of the problem is that dot is a delimiter, just like dash and slash and the old logic expected something to stand between two delimiters, now the logic is a bit smarter and it just needs to know that it is a delimiter to terminate parameters

**Comment by Fenny** [comment] 2020-08-17 09:57
https://github.com/gofiber/fiber/releases/tag/v1.14.2

**Closed** 2020-08-17 09:57 UTC
Labels: Status: Waiting to be tagged, Type: Bug
