### ISSUE TITLE
🐛 [Bug]:Incorrect log depth when use log.WithContext 

### ISSUE THREAD

**Issue by 0xmkzt** [gofiber/fiber#2646] opened 2023-09-25 15:14 UTC
### Bug Description

When i use log.WithContext, the log depth is more deeper.

### How to Reproduce

1. Run the code snippet
2. Invoke interface `curl -i http://127.0.0.1:3000/ready`
3. You can see `...router.go:145: [Info] ready`

### Expected Behavior

Actually it should be `...main.go:14: [Info] ready`

### Fiber Version

v2.49.2

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/log"
)

func main() {
	app := fiber.New()
	app.Get("/ready", func(c *fiber.Ctx) error {
		log.Info(">>>")
		log.WithContext(c.UserContext()).Info("ready")
		log.Info("<<<")
		return c.SendString("ready")
	})
	err := app.Listen(":3000")
	if err != nil {
		log.Error(err)
		return
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment] 2023-09-25 16:03
Duplicate of https://github.com/gofiber/contrib/issues/791

**Comment by ReneWerner87** [comment] 2023-09-25 16:04
@Skyenought can you help here?

**Comment by barisbll** [comment] 2023-10-02 11:18
@ReneWerner87 if this issue is free I would like to have it as my first contribution to gofiber 😊

**Comment by nikzayn** [comment] 2023-10-02 15:38
I would like to take this up!

/assign

**Comment by Skyenought** [comment] 2023-10-07 13:26
i will fix bug in fiber soon

**Closed** 2023-10-08 09:10 UTC
Labels: ☢️ Bug
