### ISSUE TITLE
When I run the `Basic Routing` code, there are some routing matching problems🤗 

### ISSUE THREAD

**Issue by thep0y** [gofiber/fiber#1090] opened 2020-12-26 08:10 UTC
**Question description**

The responses of route `/:name` and route `/:name/:age/:gender?` are correct.
The responses of route `/:file.:ext` and route `/flights/:from-:to` and route `/api/*` are wrong:
```
Hello, dictionary.txt 👋!
👴 flights is LAX-SFO years old
👴 api is register years old
```
Which code is incorrect?

**Code snippet** _Optional_

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// GET /john
	app.Get("/:name", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("Hello, %s 👋!", c.Params("name"))
		return c.SendString(msg) // => Hello john 👋!
	})

	// GET /john/75
	app.Get("/:name/:age/:gender?", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("👴 %s is %s years old", c.Params("name"), c.Params("age"))
		return c.SendString(msg) // => 👴 john is 75 years old
	})

	// GET /dictionary.txt
	app.Get("/:file.:ext", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("📃 %s.%s", c.Params("file"), c.Params("ext"))
		return c.SendString(msg) // => 📃 dictionary.txt
	})

	// GET /flights/LAX-SFO
	app.Get("/flights/:from-:to", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("💸 From: %s, To: %s", c.Params("from"), c.Params("to"))
		return c.SendString(msg) // => 💸 From: LAX, To: SFO
	})

	// GET /api/register
	app.Get("/api/*", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("✋ %s", c.Params("*"))
		return c.SendString(msg) // => ✋ register
	})

	log.Fatal(app.Listen(":3000"))
}

```

**Comment by ReneWerner87** [comment] 2020-12-26 08:46
thanks for the report, the challenge with these routes is that they use many variable parts on the same levels, here it is important to consider the order

at fiber we get the order of the routes specified by the user to exclude possible side effects or unforeseen processes

since we have chosen this order, the router will be faster by simply processing each route one after the other, we could also sort these routes so that routes with static elements come first, but this will be quite difficult with variable parts, as these require perfect prioritization by a human, as here quite complex possibilities are possible

in real microservice cases also mostly a prefix is used, so this sorting is not important there, because not several variable parts are on the same base, like here in the root path

here is the cause described again https://github.com/gofiber/fiber/issues/1088


with this order of the route, everything is working

the fixed routes first, then those which are less variable and then the really variable ones
```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// GET /api/register
	app.Get("/api/*", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("✋ %s", c.Params("*"))
		return c.SendString(msg) // => ✋ register
	})

	// GET /flights/LAX-SFO
	app.Get("/flights/:from-:to", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("💸 From: %s, To: %s", c.Params("from"), c.Params("to"))
		return c.SendString(msg) // => 💸 From: LAX, To: SFO
	})

	// GET /dictionary.txt
	app.Get("/:file.:ext", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("📃 %s.%s", c.Params("file"), c.Params("ext"))
		return c.SendString(msg) // => 📃 dictionary.txt
	})

	// GET /john/75
	app.Get("/:name/:age/:gender?", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("👴 %s is %s years old", c.Params("name"), c.Params("age"))
		return c.SendString(msg) // => 👴 john is 75 years old
	})

	// GET /john
	app.Get("/:name", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("Hello, %s 👋!", c.Params("name"))
		return c.SendString(msg) // => Hello john 👋!
	})



	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment] 2020-12-30 12:02
@thep0y any comments or questions ? otherwise i would close the issue

**Closed** 2021-01-02 07:21 UTC
Labels: ♻ Wait for Response, 🤔 Question
