### ISSUE TITLE
🤗 [Question]: When is the Fiber v3 stable release date?

### ISSUE THREAD

**Issue by longphamdevelop** [gofiber/fiber#3179] opened 2024-10-24 04:14 UTC
### Question Description

I'm very excited about GoFiber version 3, but I've been waiting for it for quite a while. Can you let me know when the official stable release will be available?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment] 2024-10-24 05:58
Duplicate of #3179

**Closed by ReneWerner87** 2024-10-24 05:58 UTC
Labels: 🤔 Question
