### ISSUE TITLE
Custom template function not working under certain circumstances

### ISSUE THREAD

**Issue by svera** [gofiber/fiber#1202] opened 2021-03-05 08:53 UTC
**Question description**
I would like to have each route in its own go file, instead of having all controllers in a big, single file. In my application, I also add a template function, called `t()`,  to translate text to another language. The following code works:

```go
func New(idx index.Reader, libraryPath, homeDir, version string, metadataReaders map[string]metadata.Reader) *fiber.App {
	cat, err := i18n.NewCatalogFromFolder(embedded, "en")
	if err != nil {
		log.Fatal(err)
	}

	message.DefaultCatalog = cat

	var printer *message.Printer
	viewsFS, err := fs.Sub(embedded, "embedded/views")
	if err != nil {
		log.Fatal(err)
	}

	engine := template.NewFileSystem(http.FS(viewsFS), ".html")
	engine.AddFunc("t", func(key string, values ...interface{}) string {
		return printer.Sprintf(key, values...)
	})

	app := fiber.New(fiber.Config{
		Views:                 engine,
		DisableStartupMessage: true,
	})

	app.Get("/:lang", func(c *fiber.Ctx) error {
		lang := c.Params("lang")
		switch lang {
		case "es":
			printer = message.NewPrinter(language.Spanish)
		case "en":
			printer = message.NewPrinter(language.English)
		default:
			return c.SendStatus(http.StatusNotFound)
		}

		page, err := strconv.Atoi(c.Query("page"))
		if err != nil {
			page = 1
		}

		var keywords string
		var searchResults *index.Result

		keywords = c.Query("search")
		if keywords != "" {
			searchResults, err = idx.Search(keywords, page, resultsPerPage)
			if err != nil {
				return fiber.ErrInternalServerError
			}

			return c.Render("results", fiber.Map{
				"Lang":      lang,
				"Keywords":  keywords,
				"Results":   searchResults.Hits,
				"Total":     searchResults.TotalHits,
				"Paginator": pagination(maxPagesNavigator, searchResults.TotalPages, searchResults.Page, "search", keywords),
				"Title":     "search_results",
				"Version":   version,
			}, "layout")
		}
		count, err := idx.Count()
		if err != nil {
			return fiber.ErrInternalServerError
		}
		return c.Render("index", fiber.Map{
			"Lang":    lang,
			"Count":   count,
			"Title":   "Coreander",
			"Version": version,
		}, "layout")
	})

        return app
}
```

but extracting the route code to a function make the application fail with a `template: layout:9:13: executing "layout" at <t .Title>: error calling t: runtime error: invalid memory address or nil pointer dereference` error:

```go
func New(idx index.Reader, libraryPath, homeDir, version string, metadataReaders map[string]metadata.Reader) *fiber.App {
	cat, err := i18n.NewCatalogFromFolder(embedded, "en")
	if err != nil {
		log.Fatal(err)
	}

	message.DefaultCatalog = cat

	var printer *message.Printer
	viewsFS, err := fs.Sub(embedded, "embedded/views")
	if err != nil {
		log.Fatal(err)
	}

	engine := template.NewFileSystem(http.FS(viewsFS), ".html")
	engine.AddFunc("t", func(key string, values ...interface{}) string {
		return printer.Sprintf(key, values...)
	})

	app := fiber.New(fiber.Config{
		Views:                 engine,
		DisableStartupMessage: true,
	})

	app.Get("/:lang", func(c *fiber.Ctx) error {
                return searchRoute(c, printer, idx, libraryPath, homeDir, version, metadataReaders)
	})

        return app
}

func searchRoute(c *fiber.Ctx, printer *message.Printer, idx index.Reader, libraryPath, homeDir, version string, metadataReaders map[string]metadata.Reader) error {
	lang := c.Params("lang")
	switch lang {
	case "es":
		printer = message.NewPrinter(language.Spanish)
	case "en":
		printer = message.NewPrinter(language.English)
	default:
		return c.SendStatus(http.StatusNotFound)
	}

	page, err := strconv.Atoi(c.Query("page"))
	if err != nil {
		page = 1
	}

	var keywords string
	var searchResults *index.Result

	keywords = c.Query("search")
	if keywords != "" {
		searchResults, err = idx.Search(keywords, page, resultsPerPage)
		if err != nil {
			return fiber.ErrInternalServerError
		}

		return c.Render("results", fiber.Map{
			"Lang":      lang,
			"Keywords":  keywords,
			"Results":   searchResults.Hits,
			"Total":     searchResults.TotalHits,
			"Paginator": pagination(maxPagesNavigator, searchResults.TotalPages, searchResults.Page, "search", keywords),
			"Title":     "search_results",
			"Version":   version,
		}, "layout")
	}
	count, err := idx.Count()
	if err != nil {
		return fiber.ErrInternalServerError
	}
	return c.Render("index", fiber.Map{
		"Lang":    lang,
		"Count":   count,
		"Title":   "Coreander",
		"Version": version,
	}, "layout")
}
```

Am I doing something wrong, is there any other way of achieving this or is this a bug?

**Comment by ReneWerner87** [comment] 2021-03-05 10:00
could you share the template code
> layout:9:13

Looks like something you used in the template and this point has already been released.

as you probably know, fasthttp and fiber works with the principle of zero allocations, i.e. it resets variables and reuses them, that may have something to do with it, so we need to find out what is used in the template

of course, it could be that the problem is simply the idx or the map, since references are missing here, the object is copied when the function is called. 

cool would be the code of the template and the knowledge which variable causes problems here

**Comment by svera** [comment] 2021-03-05 11:15
Hi @ReneWerner87 , sure, here's a snippet of the template

```html
<!doctype html>
<html lang="{{.Lang}}" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Sergio Vera">
    <title>{{t .Title}}</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/display.css" rel="stylesheet">

    <!-- Favicons -->

    <meta name="theme-color" content="#000">

</head>
```
the offending code is in the `<title>` tag

**Comment by ReneWerner87** [comment] 2021-03-05 11:20
thank you, 
at first glance i could not find any errors unfortunately

I would like to debug the whole thing, unfortunately I don't have all the resources you use there.

can you(@svera ) give me a minimal example where everything unnecessary is removed that has nothing to do with the problem, so clean up the template and all structs that are not needed

**Comment by svera** [comment] 2021-03-05 11:45
@ReneWerner87 sure, here the fat-free code

```go
import (
	"log"

	"github.com/gofiber/fiber/v2"
	template "github.com/gofiber/template/html"
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

func main() {
	var printer *message.Printer

	engine := template.New(".", ".html")
	engine.AddFunc("t", func(key string, values ...interface{}) string {
		return printer.Sprintf("Hello world")
	})

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) error {
		return searchRoute(c, printer)
	})

	err := app.Listen(":3000")
	if err != nil {
		log.Fatal(err)
	}
}

func searchRoute(c *fiber.Ctx, printer *message.Printer) error {
	printer = message.NewPrinter(language.English)

	return c.Render("example", fiber.Map{
		"Lang":  "en",
		"Title": "search_results",
	})
}
```

```html
<!doctype html>
<html lang="{{.Lang}}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{{t .Title}}</title>
</head>
```

Thank you

**Comment by ReneWerner87** [comment] 2021-03-05 12:07
Okay, I have found the error

you set the printer new inside the function, therefore the chain outside is broken and on the variable outside that you also use in the custom function, the old printer object can no longer be accessed.

```go
app.Get("/", func(c *fiber.Ctx) error {
      printer = message.NewPrinter(language.English)
      .....
```

so you have to set the printer outside the handler helper function, but i wouldn't advise you to set the variable every time someone comes with a different language.

rather build a map with all printers for the language at the beginning and manage it so that the right printer is selected from the map depending on which language is chosen.

here is the memory error
![image](https://user-images.githubusercontent.com/7063188/110113609-a4a7a400-7db3-11eb-8107-ffd08cdc9436.png)

If this helps you and you have no further questions, please feel free to close the issue again.

**Comment by svera** [comment] 2021-03-05 13:51
Thank you very much for your assistance @ReneWerner87, I'll try what you suggest, closing the issue.

**Closed** 2021-03-05 13:50 UTC
Labels: 🔍 Under Investigation
