### ISSUE TITLE
🐛 Race condition when using logger middleware

### ISSUE THREAD

**Issue by hiraqdev** [gofiber/fiber#733] opened 2020-08-16 16:46 UTC
**Fiber version**

v1.13.3

**Issue description**

When running my application with race detector enabled, i've found an error race condition:

```
WARNING: DATA RACE
Write at 0x000001ce4518 by goroutine 46:
  github.com/gofiber/fiber/middleware.logger.func2.1()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:308 +0x1661
  github.com/gofiber/fiber/middleware.(*loggerTemplate).executeFunc()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:466 +0x227
  github.com/gofiber/fiber/middleware.logger.func2()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:250 +0x299
  github.com/gofiber/fiber.(*App).next()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:110 +0x44f
  github.com/gofiber/fiber.(*App).handler()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:134 +0x71
  github.com/gofiber/fiber.(*App).handler-fm()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:128 +0x4b
  github.com/valyala/fasthttp.(*Server).serveConn()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/server.go:2162 +0x1b1d
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/server.go:1953 +0x55
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:223 +0x104
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:195 +0x42

Previous write at 0x000001ce4518 by goroutine 31:
  github.com/gofiber/fiber/middleware.logger.func2.1()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:308 +0x1661
  github.com/gofiber/fiber/middleware.(*loggerTemplate).executeFunc()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:466 +0x227
  github.com/gofiber/fiber/middleware.logger.func2()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/middleware/logger.go:250 +0x299
  github.com/gofiber/fiber.(*App).next()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:110 +0x44f
  github.com/gofiber/fiber.(*App).handler()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:134 +0x71
  github.com/gofiber/fiber.(*App).handler-fm()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/router.go:128 +0x4b
  github.com/valyala/fasthttp.(*Server).serveConn()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/server.go:2162 +0x1b1d
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/server.go:1953 +0x55
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:223 +0x104
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:195 +0x42

Goroutine 46 (running) created at:
  github.com/valyala/fasthttp.(*workerPool).getCh()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:194 +0x1aa
  github.com/valyala/fasthttp.(*workerPool).Serve()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/workerpool.go:147 +0x679
  github.com/valyala/fasthttp.(*Server).Serve()
      /home/hiraqdev/go/pkg/mod/github.com/valyala/fasthttp@v1.15.1/server.go:1706 +0x688
  github.com/gofiber/fiber.(*App).Listen()
      /home/hiraqdev/go/pkg/mod/github.com/gofiber/fiber@v1.13.3/app.go:499 +0x277
  gitlab.com/souund/backend/ark/application/service/users.(*Service).Serve()
      /home/hiraqdev/projects/souund/backend/ark/application/service/users/rest.go:127 +0xafd
  gitlab.com/souund/backend/ark/pkg/framework.Runner()
      /home/hiraqdev/projects/souund/backend/ark/pkg/framework/app.go:22 +0x99
  main.main()
      /home/hiraqdev/projects/souund/backend/ark/main.go:27 +0xe4
```

As a note, i'm using insomnia to test my api requests, when i send a request too often (just fast clicking the `Send` button), i've found these errors.

**Code snippet**

my app:

```go
app := fiber.New()
app.Use(middleware.Logger())
app.Use(middleware.Recover())
app.Use(middleware.RequestID())
```

`fiber/middleware/logger.go` line: `308`

```go
case LoggerTagStatus:
    responseStatus = c.Fasthttp.Response.StatusCode()
    if !config.enableColors {
        return buf.WriteString(strconv.Itoa(responseStatus))
    }
```

**Comment by kiyonlin** [comment] 2020-08-16 17:09
Hey @hiraqdev thanks for reporting. 

> When running my application with race detector enabled

I'm curious about `with race detector enabled`. Do you mean `go run -race .`?

**Comment by hiraqdev** [comment] 2020-08-17 08:17
Yes @kiyonlin , using `-race`

**Comment by kiyonlin** [comment] 2020-08-17 08:36
I can't reproduce the error by using your code snippet.

Could you please provide more codes or create a simple repo which can reproduce the error?

**Comment by hiraqdev** [comment] 2020-08-17 08:42
Well, actually, now i cannot repro this issue too 😓 , but i'm quite sure that this error is happened yesterday 😓

**Comment by kiyonlin** [comment] 2020-08-17 08:45
> Well, actually, now i cannot repro this issue too 😓 , but i'm quite sure that this error is happened yesterday 😓

Ok. 

I'll close this issue first. Feel free to re-open it when you get the same issue :smile:

**Closed by kiyonlin** 2020-08-17 08:45 UTC
Labels: Type: Bug
